### ISSUE TITLE
ch09, token refresh firing twice on development and not working

### ISSUE THREAD

**Issue by eriksays** [miguelgrinberg/react-microblog#5]
on development, it seems all api calls are being fired twice.
for the token refresh /token call
the first call, it returns a new token
the second call uses the old token
from that point forward, api calls attempt to use the new token stored in the first call, but it returns 401.

**Comment by miguelgrinberg** [comment]
@eriksays Starting with React 18 effect functions are executed twice in development, so your observation is correct.

What I do not see here, is that the double call causes a problem with the auth flow, but I guess it is possible with different timings there is a problem I missed. Do you have logs for the API side, so that I can see the sequence of requests?

**Comment by hjkrannig** [comment]
Hello erik, hi miguel,
first of all thanks to you miquel writing such a well structured and working tutorial. But I' have got the same problem. The program-flow is exact like you declared. When the token is expired, the API sends a 401 code. Then the token and the refresh-token is send with put(...'/tokens'). Afterwards the token and the cookie with the refresh-token changes, to be seen in the browser localstorage and cookie. So the logic works. But mostly for the first time, sometimes with the second or third refresh, the user can not be authenticated and will be set to null. I tried with your code-examples from github v.010 -v0-11 and the bug is certainly to reproduce. To force the bug I setted ACCESS_TOKEN_MINUTES=1 in .env from microblog-api which I'm using with the  python-venv-version. The output of the flask-dev-server is attached.

[server-log.txt](https://github.com/miguelgrinberg/react-microblog/files/9926498/server-log.txt)

**Comment by hjkrannig** [comment]
...just an update: in issue #1 miguel wrote that the double call of the routes happens only in development-strict mode of react. So I loaded chapter v0.12 and made a production-build of our microblog. And ... the api-calls are fired only once and by this the refresh-token part works as expected. So thanks to erik and miquel, but I think this problem is solved. 

I found another token(?... ) problem while sending a request for a new password. The new typed in password is sent, success is flashed, but the password has not changed. I will check this further on and will open an issue when the problem is permanent.

**Comment by miguelgrinberg** [comment]
Please update your Microblog API project and let me know if the refresh issues with double effect functions reappear.

**Comment by hjkrannig** [comment]
I did! After switching to build-version
npm run build
and starting the server with
npx serve -s build
everything works fine with reliable refreshing tokens. So I got a perfect base for further development of rest-apis.
Thanks again to Miguel.

**Comment by straeter** [comment]
I also have problems with the refresh token. Could it be that there is missing an "await" in https://github.com/miguelgrinberg/react-microblog/blob/6b7a1ed7423b704c0047f2259ded2d0f6f46e870/src/MicroblogApiClient.js#L17C1-L17C50 ?

**Comment by miguelgrinberg** [comment]
@straeter that needs to be fixed, you are correct, but I do not believe that missing await can cause major problems, because this happens near the end of the function. Instead of awaiting, the not awaited promise is returned, so when the caller awaits everything should sort itself out. But regardless, the await should be there, so I'll correct the mistake.

**Comment by straeter** [comment]
@miguelgrinberg thanks for checking! Actually this resolved my problem but I have to add that I changed the rest of the code quite a bit already, so for the microblog itself it is may not be relevant
